/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedChoresRouteImport } from './routes/_authenticated/chores'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedMealsRouteImport } from './routes/_authenticated/meals'
import { Route as AuthenticatedShoppingRouteImport } from './routes/_authenticated/shopping'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChoresRoute = AuthenticatedChoresRouteImport.update({
  id: '/chores',
  path: '/chores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMealsRoute = AuthenticatedMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShoppingRoute = AuthenticatedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chores': typeof AuthenticatedChoresRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/meals': typeof AuthenticatedMealsRoute
  '/shopping': typeof AuthenticatedShoppingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chores': typeof AuthenticatedChoresRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/meals': typeof AuthenticatedMealsRoute
  '/shopping': typeof AuthenticatedShoppingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chores': typeof AuthenticatedChoresRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/meals': typeof AuthenticatedMealsRoute
  '/_authenticated/shopping': typeof AuthenticatedShoppingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/chores' | '/inventory' | '/meals' | '/shopping'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/chores' | '/inventory' | '/meals' | '/shopping'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chores'
    | '/_authenticated/inventory'
    | '/_authenticated/meals'
    | '/_authenticated/shopping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chores': {
      id: '/_authenticated/chores'
      path: '/chores'
      fullPath: '/chores'
      preLoaderRoute: typeof AuthenticatedChoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meals': {
      id: '/_authenticated/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AuthenticatedMealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shopping': {
      id: '/_authenticated/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthenticatedShoppingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChoresRoute: typeof AuthenticatedChoresRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMealsRoute: typeof AuthenticatedMealsRoute
  AuthenticatedShoppingRoute: typeof AuthenticatedShoppingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChoresRoute: AuthenticatedChoresRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMealsRoute: AuthenticatedMealsRoute,
  AuthenticatedShoppingRoute: AuthenticatedShoppingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
