/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedChoresRouteImport } from './routes/_authenticated/chores'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedMealsRouteImport } from './routes/_authenticated/meals'
import { Route as AuthenticatedShoppingRouteImport } from './routes/_authenticated/shopping'

const AuthenticatedChoresRoute = AuthenticatedChoresRouteImport.update({
  id: '/_authenticated/chores',
  path: '/chores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/_authenticated/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMealsRoute = AuthenticatedMealsRouteImport.update({
  id: '/_authenticated/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShoppingRoute = AuthenticatedShoppingRouteImport.update({
  id: '/_authenticated/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/chores': typeof AuthenticatedChoresRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/meals': typeof AuthenticatedMealsRoute
  '/shopping': typeof AuthenticatedShoppingRoute
}
export interface FileRoutesByTo {
  '/chores': typeof AuthenticatedChoresRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/meals': typeof AuthenticatedMealsRoute
  '/shopping': typeof AuthenticatedShoppingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/chores': typeof AuthenticatedChoresRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/meals': typeof AuthenticatedMealsRoute
  '/_authenticated/shopping': typeof AuthenticatedShoppingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/chores' | '/inventory' | '/meals' | '/shopping'
  fileRoutesByTo: FileRoutesByTo
  to: '/chores' | '/inventory' | '/meals' | '/shopping'
  id:
    | '__root__'
    | '/_authenticated/chores'
    | '/_authenticated/inventory'
    | '/_authenticated/meals'
    | '/_authenticated/shopping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedChoresRoute: typeof AuthenticatedChoresRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMealsRoute: typeof AuthenticatedMealsRoute
  AuthenticatedShoppingRoute: typeof AuthenticatedShoppingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/chores': {
      id: '/_authenticated/chores'
      path: '/chores'
      fullPath: '/chores'
      preLoaderRoute: typeof AuthenticatedChoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meals': {
      id: '/_authenticated/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AuthenticatedMealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shopping': {
      id: '/_authenticated/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthenticatedShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedChoresRoute: AuthenticatedChoresRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMealsRoute: AuthenticatedMealsRoute,
  AuthenticatedShoppingRoute: AuthenticatedShoppingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
